Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/MethodLength:
  Max: 30
  

Metrics/LineLength:
  Max: 160
  
Style/ParallelAssignment:
  Enabled: false
  
Style/AsciiComments:
  Enabled: false
